### ISSUE TITLE
Please add the historic code to the repository

### ISSUE THREAD

**Issue by jonasstein** [Fourmilab/ent_random_sequence_tester#3]
As far I could see no distribution relies on your new repository and its commit hashes yet.
(Checked on repology https://repology.org/project/ent/versions)

It would be great, if you could rebuild the git history and add old versions of the source too.
At least the last source from https://www.fourmilab.ch/random/random.zip would be great. So one can see in the repository what changed. Ideally add the last and some more versions.

You could recreate the git repository locally and finally force push it to github.

**Comment by jonasstein** [comment]
@Fourmilab It would be great, if you could rebuild the git history and add old versions of the source too.

**Comment by Fourmilab** [comment]
@jonasstein Thanks for your interest.  Unfortunately, the original Fourmilab author is deceased.  At present, there are no plans to rebuild git history.
